

# Source des insultes :
# https://fr.wiktionary.org/w/index.php?title=Cat%C3%A9gorie:Insultes_en_fran%C3%A7ais&pageuntil=glandeur#mw-pages

insultes_con_comme = [
    "con comme la lune",
    "con comme ses pieds",
    "con comme un balai",
    "con comme un manche",
    "con comme un steak",
    "con comme une chaise",
    "con comme une valise",
    "con comme une valise à poignée intérieure",
    "con comme une valise sans poignée",
]

insultes_prefix = [
    "sale",
    "gros"
    # TODO : enfant de, fils de, enculé de...
]

insultes_sale = [
    "abruti",
    "andouille",
    "anglo-fou",
    "appareilleuse",
    "assimilé",
    "assimilée",
    "astèque",
    "avorton",
    "bachi-bouzouk",
    "baleine",
    "baraki",
    "bâtard",
    "baudet",
    "beauf",
    "bellicole",
    "bête",
    "bête à pleurer",
    "biatch",
    "bibi",
    "bic",
    "bicot",
    "bicotte",
    "bique",
    "bite",
    "bitembois",
    "Bitembois",
    "bolos",
    "bordille",
    "boucaque",
    "boudin",
    "bouffi",
    "bouffon",
    "bouffonne",
    "bougnoul",
    "bougnoule",
    "Bougnoulie",
    "bougnoulisation",
    "bougre",
    "boukak",
    "boulet",
    "bounioul",
    "bounioule",
    "bourdille",
    "bourricot",
    "bovo",
    "branleur",
    "bridé",
    "bridée",
    "brigand",
    "brise-burnes",
    "bulot",
    "cacou",
    "cafre",
    "cageot",
    "caldoche",
    "carcavel",
    "casse-bonbon",
    "casse-couille",
    "casse-couilles",
    "cave",
    "chagasse",
    "chaoui",
    "charlot de vogue",
    "charogne",
    "chauffard",
    "chbeb",
    "cheveux bleus",
    "chiabrena",
    "chien de chrétien",
    "chiennasse",
    "chienne",
    "chier",
    "chieur",
    "chieuse",
    "chinetoc",
    "chinetoque",
    "Chinetoque",
    "chintok",
    "chleuh",
    "chnoque",
    "choucroutard",
    "citrouille",
    "coche",
    "colon",
    "complotiste",
    "con",
    "conasse",
    "conchier",
    "Conchita",
    "connard",
    "connarde",
    "connasse",
    "connaud",
    "conspirationniste",
    "contracibête",
    "couille molle",
    "counifle",
    "courtaud",
    "courtaude",
    "CPF",
    "crétin",
    "crevure",
    "cricri",
    "crotté",
    "crouïa",
    "crouillat",
    "crouille",
    "croûton",
    "dago",
    "débile",
    "doryphore",
    "doxosophe",
    "doxosophie",
    "drouille",
    "du schnoc",
    "ducon",
    "duconnot",
    "dugenoux",
    "dugland",
    "duschnock",
    "emmanché",
    "emmerdeur",
    "emmerdeuse",
    "empafé",
    "empaffé",
    "empapaouté",
    "enculé",
    "enculé de ta race",
    "enfant de fusil",
    "enfant de garce",
    "enfant de putain",
    "enfant de pute",
    "enfant de salaud",
    "enflure",
    "enfoiré",
    "envaselineur",
    "épais",
    "espingoin",
    "espingouin",
    "étron",
    "face de chien",
    "face de craie",
    "face de pet",
    "face de rat",
    "fachiste",
    "FDP",
    "fell",
    "fils de bâtard",
    "fils de chien",
    "fils de chienne",
    "fils de garce",
    "fils de pute",
    "fils de ta race",
    "fiotte",
    "floco",
    "folle",
    "fouteur",
    "foutriquet",
    "fripouille",
    "frisé",
    "fritz",
    "Fritz",
    "fumelard",
    "fumier",
    "garage à bites",
    "garce",
    "gaupe",
    "gestapette",
    "Gestapette",
    "gland",
    "glandeur",
    "glandeuse",
    "glandouillou",
    "glandu",
    "glandue",
    "gnoul",
    "gnoule",
    "Godon",
    "gogol",
    "gogole",
    "gogolito",
    "goï",
    "gook",
    "gouilland",
    "gouine",
    "goulou-goulou",
    "gourdasse",
    "gourde",
    "gourgandine",
    "grognasse",
    "gueniche",
    "guide de merde",
    "guindoule",
    "habitant",
    "halouf",
    "hippopotame",
    "imbécile",
    "incapable",
    "islamo-gauchiste",
    "islamogauchiste",
    "islamo-racaille",
    "jean-foutre",
    "jean-fesse",
    "jeannette",
    "journalope",
    "judéo-bellicisme",
    "judéo-belliciste",
    "judéo-bolchévisme",
    "judéobellicisme",
    "judéobelliciste",
    "juivaillon",
    "karlouche",
    "kawish",
    "khel",
    "Khmer rose",
    "Khmer rouge",
    "Khmer vert",
    "kikoo",
    "kikou",
    "koreaboo",
    "Kraut",
    "krouia",
    "kung flu",
    "lâche",
    "lâcheux",
    "lavette",
    "loche",
    "lopette",
    "lorpidon",
    "lourpidon",
    "macaroni",
    "magot",
    "makoumé",
    "mal blanchi",
    "mange-merde",
    "mangeux de marde",
    "marchandot",
    "margouilliste",
    "marlouf",
    "marsouin",
    "marsouine",
    "mauviette",
    "maya",
    "melon",
    "mercon",
    "merdaille",
    "merdaillon",
    "merde",
    "merdeux",
    "merdouillard",
    "michto",
    "minable",
    "minus",
    "misérable",
    "moinaille",
    "moins-que-rien",
    "mollusque",
    "monacaille",
    "mongol",
    "mongol à batteries",
    "moricaud",
    "mort aux vaches",
    "morue",
    "moule à gaufres",
    "moule à merde",
    "mouloud",
    "naze",
    "nazi",
    "nèg",
    "négraille",
    "nègre",
    "nègre d’Océanie",
    "négresse",
    "négro",
    "newfie",
    "nez de bœuf",
    "niac",
    "niafou",
    "niaiseux",
    "niakoué",
    "nodocéphale",
    "nœud",
    "noob",
    "nord-phocéen",
    "NTM",
    "ntr",
    "nul",
    "nulle",
    "orchidoclaste",
    "ordure",
    "ortho",
    "pakos",
    "panoufle",
    "patarin",
    "PD",
    "peau",
    "peau d’hareng",
    "peau de couille",
    "peau de fesse",
    "peau de vache",
    "pecque",
    "pédale",
    "pédé",
    "pédoque",
    "pelle à merde",
    "péquenaud",
    "personnage de comédie",
    "petite bite",
    "petite merde",
    "pignouf",
    "pignoufe",
    "pissou",
    "pithécanthrope",
    "planche à repasser",
    "pleutre",
    "plouc",
    "pochard",
    "poissonnière",
    "pompe à vélo",
    "porc",
    "porcas",
    "porcasse",
    "pot de merde",
    "pouf",
    "pouffiasse",
    "poufiasse",
    "poundé",
    "pourriture",
    "punaise",
    "putain",
    "putain de ta race",
    "pute",
    "pute borgne",
    "putois",
    "raclure",
    "raclure de bidet",
    "radoteur",
    "rat",
    "raté",
    "raton",
    "résidu de capote",
    "résidu de fausse couche",
    "ripopée",
    "robespierrot",
    "roi des cons",
    "roi nègre",
    "rond de chiotte",
    "rosbif",
    "roulure",
    "sac à foutre",
    "sac à merde",
    "sac à papier",
    "sagouin",
    "sagouine",
    "salaud",
    "salaude",
    "sale",
    "salop",
    "salope",
    "sans-couilles",
    "satrouille",
    "sauvage",
    "sauvagesse",
    "schbeb",
    "schlague",
    "schleu",
    "Schleu",
    "Schleue",
    "schnock",
    "schnoque",
    "sent-la-pisse",
    "sidi",
    "social-traître",
    "sorcière",
    "sottiseux",
    "sous-merde",
    "stéarique",
    "tache",
    "tafiole",
    "tantouserie",
    "tantouze",
    "tapette",
    "tapettitude",
    "tarlouze",
    "tata",
    "tchoutche",
    "tebé",
    "tête carrée",
    "tête de boche",
    "tête de cochon",
    "tête de con",
    "tête de gland",
    "tête de linotte",
    "tête de mort",
    "tête de mule",
    "tête de nœud",
    "tête de veau",
    "téteux",
    "teub",
    "teubé",
    "Thénardier",
    "thon",
    "tocard",
    "tonnerre",
    "traînée",
    "travail d’Arabe",
    "triple buse",
    "trou de cul",
    "trouduc",
    "truiasse",
    "truie",
    "vaurien",
    "vaurienne",
    "vendu",
    "vert-de-gris",
    "vide-couilles",
    "viédase",
    "vieille conne",
    "vieux",
    "vieux blanc",
    "vieux con",
    "vipère lubrique",
    "visage à deux faces",
    "xéropineur",
    "youpin",
    "youtre",
    "zemel",
    "zguègue",
    "zoulette"
]
